### ISSUE TITLE
Hello Darksword!

### ISSUE THREAD

**Issue by neil501** [DarkStarSword/miasmata-fixes#7]
Hi i wanted to know if you made a trainer or some kind of mod where you can add items to your inventory? I remember when i 1st played this game i had some kind of cheat or mod where i was able to tweek my characters speed and i was able to add or take away items but i dont recall where i got it from. Is this program you made able to do that?? If not do you know of any trainer/mod that i can use to maybe help my character to be a little bit faster? It normally takes me about 3-4 days before i can get away from milo I'm not good at getting away but with extreme patience i can normally wait him out. But i dont want to do that so i was hoping for some kind of mod. Can you assist me in finding such a mod or trainer?

**Comment by neil501** [comment]
never mind! this is what i was looking for! thankm you so much the only thing i am missing is how can i tell what plant 18 is? or plant 20 or plant 33???? do you have like a chart or something so i can figure out what plant numbers???? so i can write down plant number corresponding to the plant it represents????

**Comment by DarkStarSword** [comment]
I didn't create the trainer you are referring to, but you can absolutely use miasmod to do what you want with a bit of tinkering - I never released an official mod for it, but I did mess around with massively increasing the players speed and jump height to make it feel more like playing as superman at one point ;-)

I don't recall exactly which values I tweaked for that, but IIRC they are all under something like player or physics and have somewhat obvious names - if you crack open the environment database in miasmod and poke around you can probably work it out. If you are increasing speed you will want to also alter the threshold for the player tripping over otherwise you will have a comically bad time ;-P

More info on Miasmod and links to download here: https://steamcommunity.com/app/223510/discussions/0/630800445647188169/

Alternatively, if you just want to remove the creature altogether you can use ailurophobia.miasmod from https://github.com/DarkStarSword/miasmata-fixes/releases/download/miasmod-v1.0/miasmata-mods.zip

Miasmod can also alter your save file (click open saves.dat) if you want to cheat and add an item to your inventory. I'd suggest saving your game while holding an item to see what that looks like in the save file then experiment with altering it to a different item.

OTOH the creature isn't that hard to deal with if you know a few tricks and it can be pretty rewarding to learn this, though it can still catch even experienced players unaware sometimes. A couple of things I remember off hand:
- The creature will not spawn during the first two days of the game at all.
- If you increase your perception (permanently or temporarily) you can sense if the creature has spawned by crouching - even if it is still far away and hasn't detected you yet and you don't yet hear your heartbeat. Some people play the game crouching every 30 seconds to make absolutely sure they always have the upper hand. Once the creature symbol appears get into cover and don't move - the creature will usually wander over to your rough location, but shouldn't find you and will wander off and despawn.
- If you wait until you hear the heartbeat the creature may have already spotted you and the encounter will be much more difficult.
- The creature can hear you moving even if it can't see you, so when it is nearby resist the urge to move to slightly better cover as doing so will give away your approximate position and the creature will come and investigate. Don't worry if the creature symbol turns red as the creature moves around - that means the creature could spot you, not that it has spotted you. If you move it will hear you and look in your direction and then almost certainly will spot you.
- The creature can smell you even if it can't see/hear you - this is why it always seems to know roughly where you are even if you got into cover well in advance. As long as it doesn't actually spot you (or bump into you if you are particularly unlucky) it won't agro and will just wander off.
- if the creature has spotted you, hitting it with a thrown item will blind it for several seconds giving you a chance to escape or get back into cover.
- Waving burning branches in front of the creature will mesmerise it so it will not attack. Continue doing this while planning your escape in a tight situation.
- If you enter the vicinity of a safe area the creature will immediately flee and despawn (sometimes it may glitch instead). Safe areas include all camps, as well as any of the many urns and fireplaces scattered around the island once you have lit them (I did not realise the purpose of these urns on my first playthrough - lighting them will also save your game as well as making the area safe).
- Sometime the creature glitches out and starts running in circles. If this happens it will not wander off by itself no matter how good your cover is and your only option will be to pick a direction and run. Usually the creature will stay in its circle until you are far enough away from it to despawn it, but sometimes it might unglitch and give chase - so, try to choose a direction that leads to cover or a safe space. I'm not positive, but I think this glitching can happen if the creature is trying to flee due to being too close to a safe area, but it's AI hasn't found an escape route that it can reach with it's wide turning circle while running.
- The creature can wade into the water, but it cannot swim past a certain depth - once you have increased your strength enough that you don't just drown immediately yourself crossing a river can become a viable means of escape.
- Hurling yourself off a cliff that the creature is unable to traverse can be a viable escape strategy, though you will need to take/synthesise medicine afterwards.
- Whether the creature is docile or aggressive depends on where on the island it spawned. Massive spoiler, but here are all the spawn locations colour coded by agressiveness: http://valen.darkstarsword.net/miasmata/off-topic/markers.jpg
- The creature stops spawning once you have synthesised the cure, allowing you to explore the rest of the island in peace.

**Comment by DarkStarSword** [comment]
I've got copies of all the plants journal entries here that you can use to work out which plant is which number: http://valen.darkstarsword.net/miasmata/textures/plants/

I also have maps of all the plant locations (and every other item in the game), but have only uploaded ones that people have specifically asked about. Let me know if you need any of these.

**Comment by neil501** [comment]
Hi darksword,
                        I needed to know the plants #'s for the save editor and you actually have it!!!! How awesome are you!!! I see a lot of time was put into this game by you for you to collect all this stuff. I used to play about 9 years ago all the time and just recently i was going thru a external hard drive i had and found miasmata and decided to play and now i'm back into playing it again. I just love the adventure this game is so unique compared to everything else out there I wanted to thank you for your prompt reply i figured ok 7 years old since all the replies were made he may not even have the same email so i'm glad it worked. I hope in time a new updated version comes out where players can make their own camp after they survey the surrounding land or they tell the story of the 1st group of scientist to go to the island the ones that built all the camps trying to find a cure and as a bonus in multiplayer one player can be a monster hunting players trying to find a cure! Ok I just want to say thank you! Take care!

                                                                                                                                                                                               Matrix501  :)

    On Friday, March 5, 2021, 06:28:13 PM EST, Ian Munsie <notifications@github.com> wrote:  
 
 


I've got copies of all the plants journal entries here that you can use to work out which plant is which number: http://valen.darkstarsword.net/miasmata/textures/plants/

I also have maps of all the plant locations (and every other item in the game), but have only uploaded ones that people have specifically asked about. Let me know if you need any of these.

**Comment by neil501** [comment]
Thank you so much this is great! Now i can make the game longer or shorter if i want personally i'd never get rid of milo as it really gets rid of half the game and it's fun running from him! Thanks again!
